# Generated by Django 5.1.4 on 2024-12-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.TextField()),
                ('mitre_threat_no', models.TextField()),
                ('description', models.TextField()),
                ('timestamp', models.TextField()),
            ],
        ),
    ]
